article:
    path: /articles/{id}/{version}/{part}
    controller: Libero\ApiDummy\Controller\ArticleController
    requirements:
        id: '[A-Za-z0-9\-._]+'
        version: '[1-9][0-9]*|latest'
    defaults:
        part: 'front'
